#Configuration for Chancecraft 0.2

General:
    DebugPrint: false
    CommandPrint: false
    DetailPlayerPrint: true
    ReturnOnFail: false
    TossOnFail: false
    
## Template to add an item.
## Only supports itemID and blockID,
## Always start an itemnumber with an 'i' !
#    i<ItemID>:
#        NormalChance: <0-100>
#        ProfessionExclusive: <true/false>
#        Professions:
#            <professionName>:
#                ProfessionChance0: <0-100>
#                ProfessionChanceMin: <0-100>
#                ProfessionChanceMax: <0-100>
#                MinProflvl: <0-100>
#                MaxProflvl: <0-100>

Items: